version: 2
jobs:
   build:
     machine: true
     steps:
       - checkout
       - run: docker build -t circleci-containers .
       - run: docker run -d -p 80:80 circleci-containers; sleep 10
       - run: curl --retry 10 --retry-delay 5 -v http://localhost:80               
workflows:
   version: 2
   test-trigger:
     triggers:
       - schedule:
           cron: "30 1 * * *"
           filters:
             branches:
               only: master
     jobs: 
       - build